"""Additive-only column/constraint migrations for tables that may already
exist in a deployed database (`create_all()` only creates missing tables, it
never alters or adds constraints to existing ones). No column or row is ever
dropped or deleted automatically.

Proportionate to this project's current scale (one environment, no Alembic
version history yet) - replace with real Alembic migrations if that changes.
"""

from sqlalchemy import inspect, text

_USERS_COLUMNS_TO_ADD = {
    "avatar_key": "VARCHAR(500) NULL",
}

_RECIPE_COLUMNS_TO_ADD = {
    "image_key": "VARCHAR(500) NULL",
    "owner_sub": "VARCHAR(64) NULL",
    "owner_email": "VARCHAR(255) NULL",
    "created_at": "DATETIME NULL DEFAULT CURRENT_TIMESTAMP",
    "updated_at": "DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",
}

_AI_CONVERSATIONS_COLUMNS_TO_ADD = {
    "summarized_through_message_id": "INT NULL",
}

_AI_MESSAGES_CONVERSATION_FK_NAME = "fk_ai_messages_conversation_id"


def run_migrations(engine):
    inspector = inspect(engine)

    if "users" in inspector.get_table_names():
        existing = {col["name"] for col in inspector.get_columns("users")}
        with engine.begin() as conn:
            for col, defn in _USERS_COLUMNS_TO_ADD.items():
                if col not in existing:
                    conn.execute(text(f"ALTER TABLE users ADD COLUMN {col} {defn}"))

    if "recipes" in inspector.get_table_names():
        existing_columns = {col["name"] for col in inspector.get_columns("recipes")}

        with engine.begin() as connection:
            for column_name, column_definition in _RECIPE_COLUMNS_TO_ADD.items():
                if column_name not in existing_columns:
                    connection.execute(
                        text(f"ALTER TABLE recipes ADD COLUMN {column_name} {column_definition}")
                    )

            existing_indexes = {idx["name"] for idx in inspector.get_indexes("recipes")}
            if "owner_sub" not in existing_columns and "ix_recipes_owner_sub" not in existing_indexes:
                connection.execute(text("CREATE INDEX ix_recipes_owner_sub ON recipes (owner_sub)"))

    if "ai_conversations" in inspector.get_table_names():
        existing_columns = {col["name"] for col in inspector.get_columns("ai_conversations")}
        with engine.begin() as connection:
            for column_name, column_definition in _AI_CONVERSATIONS_COLUMNS_TO_ADD.items():
                if column_name not in existing_columns:
                    connection.execute(
                        text(f"ALTER TABLE ai_conversations ADD COLUMN {column_name} {column_definition}")
                    )

    _ensure_ai_messages_conversation_fk(engine, inspector)


def _is_conversation_fk(fk):
    """True if `fk` (an inspector.get_foreign_keys() entry) is equivalent to
    the ai_messages.conversation_id -> ai_conversations.id constraint,
    regardless of its constraint name. On a fresh database created before the
    model declared an explicit name, MySQL may have assigned an
    autogenerated name (e.g. ai_messages_ibfk_1) instead of
    fk_ai_messages_conversation_id - checked by column/table shape instead of
    by name so that case is still recognized as "already present"."""
    return (
        list(fk.get("constrained_columns") or []) == ["conversation_id"]
        and fk.get("referred_table") == "ai_conversations"
        and list(fk.get("referred_columns") or []) == ["id"]
    )


def _ensure_ai_messages_conversation_fk(engine, inspector):
    """Adds the ai_messages -> ai_conversations foreign key to an
    already-existing ai_messages table that predates the FK being added to
    the model (a brand-new table created by `create_all()` already has it,
    since the model now declares it - this function is only relevant to a
    table that was created by an earlier version of the model).

    Refuses to guess: if orphaned rows are found, or the ALTER itself fails,
    this raises a clear RuntimeError so app startup fails loudly and
    deployment stops, instead of leaving the schema silently inconsistent.
    No row is ever deleted automatically.
    """
    if "ai_messages" not in inspector.get_table_names():
        return

    if any(_is_conversation_fk(fk) for fk in inspector.get_foreign_keys("ai_messages")):
        # An equivalent FK already exists - whether it has our deterministic
        # name (a table created fresh by create_all() with the current model)
        # or an autogenerated name (a table created by an earlier version of
        # the model, before the FK had an explicit name). Either way, adding
        # another one would be a duplicate constraint on the same column.
        return

    with engine.connect() as connection:
        orphan_count = connection.execute(text(
            "SELECT COUNT(*) FROM ai_messages m "
            "LEFT JOIN ai_conversations c ON m.conversation_id = c.id "
            "WHERE c.id IS NULL"
        )).scalar()

    if orphan_count:
        raise RuntimeError(
            f"Cannot add {_AI_MESSAGES_CONVERSATION_FK_NAME}: {orphan_count} "
            "row(s) in ai_messages reference a conversation_id with no "
            "matching ai_conversations.id. Refusing to delete data "
            "automatically - inspect and resolve these rows manually, then "
            "restart the app so this migration can run again."
        )

    try:
        with engine.begin() as connection:
            connection.execute(text(
                f"ALTER TABLE ai_messages "
                f"ADD CONSTRAINT {_AI_MESSAGES_CONVERSATION_FK_NAME} "
                "FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id) "
                "ON DELETE CASCADE"
            ))
    except Exception as exc:
        raise RuntimeError(
            f"Failed to add {_AI_MESSAGES_CONVERSATION_FK_NAME} to ai_messages: {exc}"
        ) from exc
